# Generated by Django 4.1.7 on 2023-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PATIENT', 'patient'), ('ADMINISTRATOR', 'administrator')], default='PATIENT', max_length=20, verbose_name='user type'),
        ),
    ]
