user_registration_info = {
    "email": "i@gmail.com",
    "password": "philip1234@i)",
    "first_name": "increase",
    "last_name": "odeyemi",
    "middle_name": "Ayobami",
    "street": "No 17 Adegbemileke street Afromed",
    "state": "Lagos",
    "city": "Ojo",
    "region": "AF",
    "country": "NG",
    "contact_no": "070780079",
    "date_of_birth": "1999-07-08",
    "gender": "MALE",
}
